# Generated by Django 4.0.4 on 2022-05-13 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0002_dish_photo_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_statuc',
            new_name='order_status',
        ),
    ]
