# Generated by Django 4.0.4 on 2022-05-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0004_alter_order_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_priority',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
