# Generated by Django 4.0.4 on 2022-05-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('customer_num', models.IntegerField()),
                ('reservation_date', models.CharField(max_length=10)),
                ('reservation_time', models.CharField(max_length=10)),
            ],
        ),
    ]
